#cloud-config
users:
  - name: attacker
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - "{{ ssh_public_key }}"

packages:
  - nmap
  - netcat-traditional
  - tcpreplay
  - wget

runcmd:
  - [ bash, -c, "mkdir -p /root/attacks && chmod 700 /root/attacks" ]
  - [ bash, -c, "cat > /root/run_attack.sh <<'EOF'\n#!/bin/bash\nsleep 30\nnmap -sS -Pn 192.168.70.30 -oN /root/attacks/nmap_scan.txt || true\nfor i in $(seq 1 5); do printf 'GET / HTTP/1.1\\r\\nHost: 192.168.70.30\\r\\n\\r\\n' | nc 192.168.70.30 80 || true; sleep 2; done\nif [ -f /root/attacks/malicious.pcap ]; then tcpreplay --intf1=eth0 /root/attacks/malicious.pcap || true; fi\necho 'done'\nEOF" ]
  - [ bash, -c, "chmod +x /root/run_attack.sh" ]
